ems-dev:
  type: ems
  url: "tcp://tibco-dev:11200"
  username: "admin"
  password: "encr:02f13e62:b71b713aca76fb066e5bf9a1261ffa0e1e1729c8839436e1bbf6c4f37e5f4d59ded07775"

routes:
  - name: folder-to-ems
    from: "fs:./data/in"
    to:
      - "ems-dev:queue:tmp.q"
      - "fs:./data/out"
